package com.mycompany.tenvappelabs;
import java.awt.Component;
import com.mycompany.tenvappelabs.view.menuDashboard;
import com.mycompany.tenvappelabs.view.inbox;
import com.mycompany.tenvappelabs.view.customer;
import com.mycompany.tenvappelabs.view.promosi;
public class DashboardAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DashboardAdmin
     */
    public DashboardAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_kiri = new javax.swing.JPanel();
        logoTV = new javax.swing.JLabel();
        b_dashboard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panel_kanan = new javax.swing.JPanel();
        t_selamat = new javax.swing.JPanel();
        t_selamatDatang = new javax.swing.JLabel();
        t_tenVape = new javax.swing.JLabel();
        panel_dasar = new javax.swing.JPanel();
        panel_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_kiri.setBackground(new java.awt.Color(0, 102, 102));

        logoTV.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        logoTV.setForeground(new java.awt.Color(255, 255, 255));
        logoTV.setText("TenVape");

        b_dashboard.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        b_dashboard.setForeground(new java.awt.Color(255, 255, 255));
        b_dashboard.setText("Dashboard");
        b_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_dashboardMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Inbox");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customers");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Promosi");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_kiriLayout = new javax.swing.GroupLayout(panel_kiri);
        panel_kiri.setLayout(panel_kiriLayout);
        panel_kiriLayout.setHorizontalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_kiriLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(logoTV))
                    .addGroup(panel_kiriLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1))
                    .addGroup(panel_kiriLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(b_dashboard)))
                    .addGroup(panel_kiriLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel3)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        panel_kiriLayout.setVerticalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(logoTV)
                .addGap(70, 70, 70)
                .addComponent(b_dashboard)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(781, Short.MAX_VALUE))
        );

        getContentPane().add(panel_kiri, java.awt.BorderLayout.LINE_START);

        panel_kanan.setBackground(new java.awt.Color(204, 204, 204));
        panel_kanan.setPreferredSize(new java.awt.Dimension(1200, 800));
        panel_kanan.setLayout(new java.awt.BorderLayout());

        t_selamat.setBackground(new java.awt.Color(255, 255, 255));

        t_selamatDatang.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        t_selamatDatang.setText("Selamat Datang");

        t_tenVape.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        t_tenVape.setText("Profil");

        javax.swing.GroupLayout t_selamatLayout = new javax.swing.GroupLayout(t_selamat);
        t_selamat.setLayout(t_selamatLayout);
        t_selamatLayout.setHorizontalGroup(
            t_selamatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(t_selamatLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(t_selamatDatang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1227, Short.MAX_VALUE)
                .addComponent(t_tenVape)
                .addGap(52, 52, 52))
        );
        t_selamatLayout.setVerticalGroup(
            t_selamatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(t_selamatLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(t_selamatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_selamatDatang)
                    .addComponent(t_tenVape))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panel_kanan.add(t_selamat, java.awt.BorderLayout.PAGE_START);

        panel_dasar.setBackground(new java.awt.Color(250, 250, 250));
        panel_dasar.setToolTipText("");
        panel_dasar.setPreferredSize(new java.awt.Dimension(1051, 600));

        panel_utama.setPreferredSize(new java.awt.Dimension(950, 500));
        panel_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout panel_dasarLayout = new javax.swing.GroupLayout(panel_dasar);
        panel_dasar.setLayout(panel_dasarLayout);
        panel_dasarLayout.setHorizontalGroup(
            panel_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dasarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 1304, Short.MAX_VALUE)
                .addGap(92, 92, 92))
        );
        panel_dasarLayout.setVerticalGroup(
            panel_dasarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dasarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        panel_kanan.add(panel_dasar, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel_kanan, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dashboardMouseEntered
        
    }//GEN-LAST:event_b_dashboardMouseEntered

    private void b_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dashboardMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_b_dashboardMouseExited

    private void b_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_dashboardMouseClicked
        panel_utama.removeAll();
        panel_utama.add(new menuDashboard());
        panel_utama.repaint();
        panel_utama.revalidate();
        
    }//GEN-LAST:event_b_dashboardMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        panel_utama.removeAll();
        panel_utama.add(new inbox());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        panel_utama.removeAll();
        panel_utama.add(new customer());
        panel_utama.repaint();
        panel_utama.revalidate();

    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        panel_utama.removeAll();
        panel_utama.add(new promosi());
        panel_utama.repaint();
        panel_utama.revalidate();

    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DashboardAdmin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel b_dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logoTV;
    private javax.swing.JPanel panel_dasar;
    private javax.swing.JPanel panel_kanan;
    private javax.swing.JPanel panel_kiri;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JPanel t_selamat;
    private javax.swing.JLabel t_selamatDatang;
    private javax.swing.JLabel t_tenVape;
    // End of variables declaration//GEN-END:variables
}
